<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Roomkey_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get roomkey by room_number
     */
    function get_roomkey($room_number)
    {
        return $this->db->get_where('roomkeys',array('room_number'=>$room_number))->row_array();
    }
        
    /*
     * Get all roomkeys
     */
    function get_all_roomkeys()
    {
        $this->db->order_by('room_number', 'desc');
        $this->db->where('enddate >', date('Y-m-d'));
        return $this->db->get('roomkeys')->result_array();
    }
        
    /*
     * function to add new roomkey
     */
    function add_roomkey($params)
    {
        $this->db->insert('roomkeys',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update roomkey
     */
    function update_roomkey($room_number,$params)
    {
        $this->db->where('room_number',$room_number);
        return $this->db->update('roomkeys',$params);
    }
    
    /*
     * function to delete roomkey
     */
    function delete_roomkey($room_number)
    {
        return $this->db->delete('roomkeys',array('room_number'=>$room_number));
    }
}
